[Prefix = "preemo::"]
interface Root {
	void Root();
	boolean StartUp(VoidPtr windowPtr);
	void Run(Scene scene);
	boolean hasCompletedStartUp();
};

[Prefix = "preemo::"]
interface Entity {
	void Entity();
	//any AddComponent(DOMString id);
	//boolean HasComponent(DOMString id);
	[Value] TransformComponent AddComponentTransform();
	boolean HasComponentTransform();
};

[Prefix = "preemo::"]
interface Scene {
	void Scene();
	[Value] Entity CreateEntity();
};

[Prefix = "preemo::"]
interface TransformComponent {
	//long testValue;
	long getTestValue();
	void TransformComponent();
};

